stages:
  - test
  - build
  - security

include:
  - project: 'meganerd/ci-templates'
    file: '/go/test.yml'
    ref: 'v1.0.0'
  - project: 'meganerd/ci-templates'
    file: '/go/lint.yml'
    ref: 'v1.0.0'
  - project: 'meganerd/ci-templates'
    file: '/go/build.yml'
    ref: 'v1.0.0'
  - project: 'meganerd/ci-templates'
    file: '/go/security.yml'
    ref: 'v1.0.0'

variables:
  GO_BUILD_PATH: "./cmd/pi-go/"
  GO_BINARY_NAME: "pi-go"
  GO_VERSION_PKG: "github.com/meganerd/pi-go/internal/version"
  GO_TEST_EXTRA_PACKAGES: "ripgrep"
