linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - misspell
    - gofmt

linters-settings:
  errcheck:
    check-blank: true
  govet:
    enable-all: true
    disable:
      - fieldalignment

issues:
  exclude-use-default: false
  max-issues-per-linter: 50
  max-same-issues: 10
